# Include the default make file.
include ../lib/Main.mk

# Optionally set the name of the executable to compile.
#EXEC = main.out

# Optionally set any extra library information.
#ADDITIONAL_LIBRARY = 
#ADDITIONAL_HEADERS = .
#ADDITIONAL_LIBRARY_PATH = .